--- #YAML:1.0
distribution_type: module
name: WWW-Yahoo-Groups
version: 1.8.3
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.10
  Test::Pod: 0.95
requires:
  WWW::Mechanize: 0.51
  Params::Validate: 0.62
  IO::Socket::SSL: 0.94
  Exception::Class: 1.13
  HTML::Entities: 1.25
  HTTP::Cookies: 1.30

private:
  directory:
    - examples
    - t

provides:
  WWW::Yahoo::Groups:
    file: lib/WWW/Yahoo/Groups.pm
    version: 1.83
  WWW::Yahoo::Groups::Errors:
    file: lib/WWW/Yahoo/Groups/Errors.pm
    version: ~
  WWW::Yahoo::Groups::Mechanize:
    file: lib/WWW/Yahoo/Groups/Mechanize.pm
    version: ~

generated_by: docmaker version 0.89
