--- #YAML:1.0
name: WWW-Yahoo-Groups
version: 1.8.1
license: perl
distribution_type: module
requires:
  Exception::Class: 1.12
  HTML::Entities: 1.25
  HTTP::Cookies: 1.30
  IO::Socket::SSL: 0.91
  Locale::Maketext: 1.05
  Locale::Maketext::Lexicon: 0.26
  Net::HTTPS: 0.01
  Params::Validate: 0.58
  perl: 5.6.0
recommends:
  File::Find::Rule: 0.10
  Test::Pod: 0.95
  Test::Signature: 1.04
build_requires:
  Module::Signature: 0.13
  Test::More: 0.47
conflicts: {}
provides:
  Build:
    file: Build.pm
    version: 0.11
  WWW::Yahoo::Groups::Errors:
    file: lib/WWW/Yahoo/Groups/Errors.pm
    version: ~
  WWW::Yahoo::Groups::L10N:
    file: lib/WWW/Yahoo/Groups/L10N.pm
    version: 1.00
  WWW::Yahoo::Groups::L10N::_stub:
    file: lib/WWW/Yahoo/Groups/L10N.pm
    version: ~
  WWW::Yahoo::Groups::Mechanize:
    file: lib/WWW/Yahoo/Groups/Mechanize.pm
    version: >-
      Can't locate WWW/Yahoo/Groups/Errors.pm in @INC (@INC contains:
      /opt/perl/5.8.0/lib/5.8.0/i686-linux /opt/perl/5.8.0/lib/5.8.0
      /opt/perl/5.8.0/lib/site_perl/5.8.0/i686-linux
      /opt/perl/5.8.0/lib/site_perl/5.8.0 /opt/perl/5.8.0/lib/site_perl .) at
      /home/iain/toys/perl/m/WWW-Yahoo-Groups/lib/WWW/Yahoo/Groups/Mechanize.pm
      line 6.
generated_by: Module::Build version 0.18
