--- #YAML:1.0
distribution_type: module
name: WWW-Yahoo-Groups
date: 30 Jul 2003
author: SPOON
version: 1.85
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
  Test::Differences: 0.47
recommends:
  File::Find::Rule: 0.11
  Test::Pod: 0.95
requires:
  Params::Validate: 0.64
  Exception::Class: 1.14
  HTML::Entities: 1.25
  HTTP::Cookies: 1.30

private:
  directory:
    - examples
    - t

provides:
  WWW::Yahoo::Groups:
    file: lib/WWW/Yahoo/Groups.pm
    version: 1.85
  WWW::Yahoo::Groups::Errors:
    file: lib/WWW/Yahoo/Groups/Errors.pm
    version: 1.85
  WWW::Yahoo::Groups::Mechanize:
    file: lib/WWW/Yahoo/Groups/Mechanize.pm
    version: 1.85

dynamic_config: 0
generated_by: docmaker version 0.91
