--- #YAML:1.0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.11
license: perl
name: WWW-Yahoo-Groups
recommends: {}
requires:
  Exception::Class: 1.07
  HTML::Entities: 1.23
  HTTP::Cookies: 1.24
  IO::Socket::SSL: 0.91
  Net::HTTPS: 0.01
  Params::Validate: 0.24
  WWW::Mechanize: 0.31
  perl: 5.6.0
version: 1.7.5
